<?php
return [
    [
        'name' => 'Visual Studio Code',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Editor di codice open source',
        'category' => 'Editor di codice',
        'release_year' => 2015,
        'latest_version' => '1.63.2',
        'download_link' => 'https://code.visualstudio.com/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.7,
    ],
    [
        'name' => 'Adobe Photoshop',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Software di fotoritocco',
        'category' => 'Grafica',
        'release_year' => 1990,
        'latest_version' => '2022',
        'download_link' => 'https://www.adobe.com/products/photoshop.html',
        'supported_os' => 'Windows, macOS',
        'vote' => 4.5,
    ],
    [
        'name' => 'Google Chrome',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Browser web sviluppato da Google',
        'category' => 'Browser web',
        'release_year' => 2008,
        'latest_version' => '98.0.4758.102',
        'download_link' => 'https://www.google.com/chrome/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.8,
    ],
    [
        'name' => 'GitHub',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Piattaforma di sviluppo collaborativo di software',
        'category' => 'Collaborazione',
        'release_year' => 2008,
        'latest_version' => null,
        'download_link' => 'https://github.com/',
        'supported_os' => 'Web',
        'vote' => 4.9,
    ],
    [
        'name' => 'MySQL',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Sistema di gestione di database relazionali',
        'category' => 'Database',
        'release_year' => 1995,
        'latest_version' => '8.0.28',
        'download_link' => 'https://www.mysql.com/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.6,
    ],
    [
        'name' => 'Node.js',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Runtime di JavaScript basato su Chrome V8',
        'category' => 'Runtime di JavaScript',
        'release_year' => 2009,
        'latest_version' => '16.14.0',
        'download_link' => 'https://nodejs.org/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.5,
    ],
    [
        'name' => 'Sublime Text',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Editor di codice leggero e veloce',
        'category' => 'Editor di codice',
        'release_year' => 2008,
        'latest_version' => '4.1.5',
        'download_link' => 'https://www.sublimetext.com/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.8,
    ],
    [
        'name' => 'Notepad++',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Editor di codice open source per Windows',
        'category' => 'Editor di codice',
        'release_year' => 2003,
        'latest_version' => '8.3.2',
        'download_link' => 'https://notepad-plus-plus.org/',
        'supported_os' => 'Windows',
        'vote' => 4.7,
    ],
    [
        'name' => 'Postman',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Client RESTful API',
        'category' => 'API',
        'release_year' => 2012,
        'latest_version' => '9.1.5',
        'download_link' => 'https://www.postman.com/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.9,
    ],
    [
        'name' => 'MongoDB',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Database non relazionale basato su documenti',
        'category' => 'Database',
        'release_year' => 2009,
        'latest_version' => '5.1.1',
        'download_link' => 'https://www.mongodb.com/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.7,
    ],
    [
        'name' => 'Atom',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Editor di codice open source',
        'category' => 'Editor di codice',
        'release_year' => 2014,
        'latest_version' => '1.54.0',
        'download_link' => 'https://atom.io/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.6,
    ],
    [
        'name' => 'React',
        'image_url' => 'https://via.placeholder.com/150',
        'description' => 'Libreria JavaScript per lo sviluppo di interfacce utente',
        'category' => 'Libreria JavaScript',
        'release_year' => 2013,
        'latest_version' => '18.0.3',
        'download_link' => 'https://reactjs.org/',
        'supported_os' => 'Web',
        'vote' => 4.7,
    ]
];
